import type { CaseItem } from "@/domain/case-item";

export const DEFAULT_CASES: Omit<CaseItem, "id" | "isActive">[] = [
  { name: "Fever Case", marketHashName: "Fever Case" },
  { name: "Gallery Case", marketHashName: "Gallery Case" },
  { name: "Kilowatt Case", marketHashName: "Kilowatt Case" },
  { name: "Revolution Case", marketHashName: "Revolution Case" },
  { name: "Recoil Case", marketHashName: "Recoil Case" },
  { name: "Dreams & Nightmares Case", marketHashName: "Dreams & Nightmares Case" },
  { name: "Operation Riptide Case", marketHashName: "Operation Riptide Case" },
  { name: "Snakebite Case", marketHashName: "Snakebite Case" },
  { name: "Fracture Case", marketHashName: "Fracture Case" },
  { name: "Operation Broken Fang Case", marketHashName: "Operation Broken Fang Case" },
  { name: "Prisma 2 Case", marketHashName: "Prisma 2 Case" },
  { name: "CS20 Case", marketHashName: "CS20 Case" },
  { name: "Shattered Web Case", marketHashName: "Shattered Web Case" },
  { name: "Prisma Case", marketHashName: "Prisma Case" },
  { name: "Danger Zone Case", marketHashName: "Danger Zone Case" },
  { name: "Horizon Case", marketHashName: "Horizon Case" },
  { name: "Clutch Case", marketHashName: "Clutch Case" },
  { name: "Spectrum 2 Case", marketHashName: "Spectrum 2 Case" },
  { name: "Operation Hydra Case", marketHashName: "Operation Hydra Case" },
  { name: "Spectrum Case", marketHashName: "Spectrum Case" },
  { name: "Glove Case", marketHashName: "Glove Case" },
  { name: "Gamma 2 Case", marketHashName: "Gamma 2 Case" },
  { name: "Gamma Case", marketHashName: "Gamma Case" },
  { name: "Chroma 3 Case", marketHashName: "Chroma 3 Case" },
  { name: "Operation Wildfire Case", marketHashName: "Operation Wildfire Case" },
  { name: "Revolver Case", marketHashName: "Revolver Case" },
  { name: "Shadow Case", marketHashName: "Shadow Case" },
  { name: "Falchion Case", marketHashName: "Falchion Case" },
  { name: "Chroma 2 Case", marketHashName: "Chroma 2 Case" },
  { name: "Chroma Case", marketHashName: "Chroma Case" },
  { name: "Operation Vanguard Weapon Case", marketHashName: "Operation Vanguard Weapon Case" },
  { name: "Operation Breakout Weapon Case", marketHashName: "Operation Breakout Weapon Case" },
  { name: "Huntsman Weapon Case", marketHashName: "Huntsman Weapon Case" },
  { name: "Operation Phoenix Weapon Case", marketHashName: "Operation Phoenix Weapon Case" },
  { name: "CS:GO Weapon Case 3", marketHashName: "CS:GO Weapon Case 3" },
  { name: "Winter Offensive Weapon Case", marketHashName: "Winter Offensive Weapon Case" },
  { name: "eSports 2013 Winter Case", marketHashName: "eSports 2013 Winter Case" },
  { name: "CS:GO Weapon Case 2", marketHashName: "CS:GO Weapon Case 2" },
  { name: "Operation Bravo Case", marketHashName: "Operation Bravo Case" },
  { name: "eSports 2013 Case", marketHashName: "eSports 2013 Case" },
  { name: "CS:GO Weapon Case", marketHashName: "CS:GO Weapon Case" },
  { name: "Sealed Genesis Terminal", marketHashName: "Sealed Genesis Terminal" },
  { name: "Sealed Dead Hand Terminal", marketHashName: "Sealed Dead Hand Terminal" },
];
